In [28]:
from numpy import array
from random import randint

In [29]:
def saisie():
    N  = int(input("donner N: "))
    while not 3 <= N <=  15:
        N = int(input("donner N (3 <= N <= 15):"))
    return N

In [30]:
def remplir_txt(N, source):
    for i in range(N):
        ch = input("donner une chaine numerique: ")
        while not ch.isdecimal():
            ch = input("donner une chaine numerique: ")
        source.write(ch + "\n")

In [31]:
def remplir_matrice(N, source, M):
    source = open("Source.txt", "r")
    i = 0
    j = 0
    while i != N:
        ch = source.readline()
        ch = ch[:len(ch) - 1]
        while j != N:
            while len(ch) != N:
                    if len(ch) > N:
                        ch = ch[: len(ch) - 1]
                    elif len(ch) < N:
                        ch = str(randint(1, 9)) + ch
            M[i, j] = ch[j]
            j += 1
        i += 1
        j = 0
    source.close()

PP


In [32]:
source = open("Source.txt", "w")
N  = saisie()
M = array([[int()] * N] * N)
T  = array([int()] * N)
remplir_txt(N, source)
source.close()
remplir_matrice(N, source, M)
print(M)

[[9 0 4 3 1]
 [8 5 5 7 2]
 [7 8 9 4 5]
 [1 2 3 4 5]
 [6 4 1 6 8]]
