In [9]:
from numpy import array
from pickle import load, dump
from random import randint

In [10]:
def saisie():
    n = int(input("donner " + str(n) + ": "))
    while n > 100:
        n = int(input("donner " + str(n) + ": "))
    return n

In [11]:
def remplir_fiche(IMG, IMGRec):
    m = int(input("donner la taille du fichier: "))

    for i in range(m):
        if i == 0:
            IMG["X"] = int(input("donner i: "))
            x = IMG["X"]
            while IMG["X"] > 100:
                IMG["X"] = int(input("donner i: "))
                x = IMG["X"]
                
            IMG["Y"] = int(input("donner j: "))
            y = IMG["Y"]
            while IMG["Y"] > 100:
                IMG["Y"] = int(input("donner j: "))
                y = IMG["Y"]
            dump(IMG, IMGRec)
        else:
            IMG["X"] = randint(0, x)
            
            while IMG["X"] >= x and IMG["X"] <= 10:
                IMG["X"] = randint(0, x)
            IMG["Y"] = randint(0, y)
            
            while IMG["Y"] >= y and IMG["Y"] <= 10:
                IMG["Y"] = randint(0, y)
            
            IMG["C"] = randint(0, 10)
            while IMG["C"] >= 10:
                IMG["C"] = randint(0, 10)
            dump(IMG, IMGRec)
            

In [12]:
def indice_x(IMGRec):
    IMGRec = open("IMGRec.dat", "rb")
    i = 0
    while i == 0:
        E = load(IMGRec)
        x = E["X"]
        i += 1
    IMGRec.close()
    return x

In [13]:
def indice_y(IMGRec):
    IMGRec = open("IMGRec.dat", "rb")
    i = 0
    while i == 0:
        E = load(IMGRec)
        y = E["Y"]
        i += 1
    IMGRec.close()
    return y

In [14]:
def remplir1(M, x, y):
    for i in range(x):
        for j in range(y):
            M[i, j] = -1

In [15]:
def remplir2(M, IMGRec):
        IMGRec = open("IMGRec.dat", "rb")

        fin_fichier = False
        while fin_fichier == False:
            try:
                E = load(IMGRec)
                i = E["X"]
                j = E["Y"]
                M[i, j] = E["C"]

            except:
                fin_fichier = True
        IMGRec.close()

In [16]:
IMG = {
    'X' : int(),
    'Y' : int(),
    'C' : int() 
}

IMGRec = open("IMGRec.dat", "wb")
remplir_fiche(IMG, IMGRec)
IMGRec.close()
x = indice_x(IMGRec)
y = indice_y(IMGRec)
M = array([[int()] * y] * x)

remplir2(M, IMGRec)
print(M)
    

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
